# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build For Testing"
  lane :build_for_testing do
	# build only
     scan(
    	project: "image-loader.xcodeproj",
    	scheme: "image-loader",
    	device: "iPhone 17 Pro",
    	xcargs: "CODE_SIGNING_ALLOWED=NO",
    	derived_data_path: "~/Library/Developer/Xcode/DerivedData",
		build_for_testing: true
     )
  end

  desc "Run Unit Tests"
  lane :test_without_building do
	 # test without building
     scan(
    	project: "image-loader.xcodeproj",
    	scheme: "image-loader",
    	device: "iPhone 17 Pro",
    	xcargs: "CODE_SIGNING_ALLOWED=NO",
    	output_types: "junit",
    	output_directory: "fastlane/test_output",
    	result_bundle: true,
    	derived_data_path: "~/Library/Developer/Xcode/DerivedData",
		test_without_building: true
     )
  end

  desc "CI Test Pipeline"
  lane :ci_test do
	build_for_testing
	test_without_building
  end

  # run this lane when certificates expire
  lane :sync_signing do
	api_key = app_store_connect_api_key(
  		key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
  		issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
  		key_content: ENV["APP_STORE_CONNECT_API_KEY_PRIVATE_KEY"]
  	)
  	match(
    	type: "appstore",
    	app_identifier: ENV["APP_IDENTIFIER"],
   		api_key: api_key
  	)
  end

  lane :beta do
    api_key = app_store_connect_api_key(
    	key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
    	issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
    	key_content: ENV["APP_STORE_CONNECT_API_KEY_PRIVATE_KEY"]
  	)

	match(
  		type: "appstore",
  		app_identifier: ENV["APP_IDENTIFIER"],
  		api_key: api_key,
  		readonly: true
	)

	latest = latest_testflight_build_number(
  		api_key: api_key
	)

  	increment_build_number(
		build_number: latest + 1,
    	xcodeproj: "image-loader.xcodeproj"
  	)

  	gym(
    	project: "image-loader.xcodeproj",
    	scheme: "image-loader",
    	clean: true,
    	export_method: "app-store",
    	output_directory: "fastlane/build",
    	output_name: "image-loader.ipa",
  		include_bitcode: false
  	)

  	upload_to_testflight(
    	api_key: api_key
  	)
  end
end
