# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :test do
     scan(
    	project: "image-loader.xcodeproj",
    	scheme: "image-loader",
    	device: "iPhone 17 Pro",
    	xcargs: "CODE_SIGNING_ALLOWED=NO",
    	output_types: "junit",
    	output_directory: "fastlane/test_output",
    	result_bundle: true
     )
  end
end
