name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-26
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v6

    - name: Run Unit Tests
      run: |
        set -eo pipefail
        
        xcode-select -p
        xcodebuild -version
        xcodebuild -showsdks
        
        echo "===== RUNTIMES ====="
        xcrun simctl list runtimes
        echo "===== DEVICES ====="
        xcrun simctl list devices available

        xcodebuild test \
          -project image-loader.xcodeproj \
          -scheme image-loader \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=latest' \
          CODE_SIGNING_ALLOWED=NO \
          -resultBundlePath TestResults.xcresult \
          -quiet

    - name: Upload Tests Results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: TestResults.xcresult
        path: TestResults.xcresult
        retention-days: 2
